### PR TITLE
1659 fix contact form layout on contact us page

### LINKED ISSUE #1659: Fix Contact Form layout on Contact Us page
### Overview
On the Contact Us page, the current contact form's styling does not match our Figma design. We need to update the form's styling and layout to match the Figma design in preparation for pre-launch.

### Action Items
- [x] Inspect the screenshots of 'current layout' & 'expected layout' below in Resources/Instructions to compare the visual difference on the forms
- [x] Review the Figma design file in Figma Resources below to inspect the CSS layout requirements such as properties for each input field on the contact form
- [x] Review the `ContactForm.jsx` component in codebase
- [x] If needed, familiarize yourself with [MUI Components](https://mui.com/components/) documentation specifically on Grids and Forms
- [x] Make changes to the codebase so that our contact form match with the Figma design
- [x] Test the changes to confirm it's bug free prior to pushing and making a pull request

### Resources/Instructions

<details><summary>Screenshot of current layout</summary>
<p>

Screenshot 2024-01-27 at 12 18 45 AM

</p>
</details> 

<details><summary>Screenshot of expected layout (from Figma)</summary>
<p>

Screenshot 2024-01-27 at 12 28 17 AM
</p>
<br>
<p>
Note: just work on the form for this issue, ignore the other design differences on the page for now

Screenshot 2024-01-27 at 12 25 03 AM

</p>
</details> 

#### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Contact Us

### PR DESCRIPTION
**Pull request by bphan002**
Fixes #1659

The issue specifically said to just work on the form so there might be some minor margin issues with the form page. Before and after of the form are attached below. 

  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [x] All PR Status checks are successful
  - [ ] Peer reviewed and approved

<details><summary>Screenshot of current layout</summary>
<p>

Screenshot 2024-02-05 at 8 04 17 PM
</p>
</details> 

<details><summary>Screenshot of changed layout</summary>
<p>

Screenshot 2024-02-05 at 8 07 42 PM

</p>
<br>
<p>

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Review by ryanfchase — CHANGES_REQUESTED** [review]
@bphan002 looks like Figma is showing that the background color for `headingBackground` needs to be `#0F181F`

**Review by ryanfchase — APPROVED** [review]
Please wait until 1 more engineer adds their review before merging

File: components/contact/Contact.jsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ function Contact() {
       </div>
       <div>
         <TextHeading>Contact Us</TextHeading>
-        <ContentBody maxWidth="sm">
+        <ContentBody maxWidth="684px">
```
Comment (jaasonw) [inline components/contact/Contact.jsx:28]: is there a reason to prefer a hard coded value here as opposed to the breakpoint we had before?

File: components/contact/ContactForm.jsx [hunk 2]
```diff
@@ -1,14 +1,36 @@
...
 import Grid from '@mui/material/Grid';
 import Button from '@mui/material/Button';
 import TextField from '@mui/material/TextField';
+import InputLabel from '@mui/material/InputLabel';
 import CircularProgress from '@mui/material/CircularProgress';
 import { showFeedbackSuccess, setErrorModal } from '@reducers/ui';
 import { sendGitRequest } from '@reducers/data';
 import 'react-toastify/dist/ReactToastify.css';
 
+const useStyles = makeStyles(theme => ({
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:14]: avoid hard coding these css values where you can, specifically colors and font weights. prefer adding them to the global theme or reusing existing defined valued in the theme


https://github.com/hackforla/311-data/blob/main/theme/

File: components/contact/ContactForm.jsx [hunk 3]
```diff
@@ -1,14 +1,36 @@
...
+  form: {
+    marginBottom: theme.spacing(20)
+  },
+  formLabel: {
+    fontSize: '18px',
+    color: '#29404F',
+    fontWeight: 500,
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:21]: a weight of 500 is predefined here: https://github.com/hackforla/311-data/blob/main/theme/fonts.js#L8

File: components/contact/ContactForm.jsx [hunk 4]
```diff
@@ -1,14 +1,36 @@
...
 import { sendGitRequest } from '@reducers/data';
 import 'react-toastify/dist/ReactToastify.css';
 
+const useStyles = makeStyles(theme => ({
+  form: {
+    marginBottom: theme.spacing(20)
+  },
+  formLabel: {
+    fontSize: '18px',
+    color: '#29404F',
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:20]: colors should either be added to the global theme or refer to an already existing color especially because of implications with dark mode

File: components/contact/ContactForm.jsx [hunk 5]
```diff
@@ -1,14 +1,36 @@
...
+    fontWeight: 500,
+    marginTop: theme.spacing(2),
+    marginBottom: theme.spacing(2),
+  },
+  formInput: {
+    backgroundColor: '#29404F1A',
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:26]: see previous comment about color

File: package.json [hunk 6]
```diff
@@ -28,6 +28,7 @@
     "@emotion/react": "^11.11.1",
     "@emotion/styled": "^11.11.0",
     "@mapbox/mapbox-gl-geocoder": "^5.0.1",
+    "@material-ui/core": "^4.12.4",
```
Comment (jaasonw) [inline package.json:31]: `@material-ui/core` is part of material ui 4, we recently moved to 5 so components from core should be imported from `@mui/material`

File: components/contact/ContactForm.jsx [hunk 7]
```diff
@@ -1,14 +1,36 @@
...
 import { showFeedbackSuccess, setErrorModal } from '@reducers/ui';
 import { sendGitRequest } from '@reducers/data';
 import 'react-toastify/dist/ReactToastify.css';
 
+const useStyles = makeStyles(theme => ({
+  form: {
+    marginBottom: theme.spacing(20)
+  },
+  formLabel: {
+    fontSize: '18px',
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:19]: likely a larger codebase issue and out of scope for this PR but we should prefer avoiding hardcoded font sizes because it has implications for mobile responsiveness

File: components/contact/ContactForm.jsx [hunk 8]
```diff
@@ -1,14 +1,36 @@
 import React, { useState, useEffect, useCallback } from 'react';
 import { useDispatch, useSelector } from 'react-redux';
 import { toast } from 'react-toastify';
+import { makeStyles } from '@material-ui/core/styles';
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:4]: `import makeStyles from '@mui/styles/makeStyles';` and remove the material-ui dependency

File: components/contact/ContactIntro.jsx [hunk 9]
```diff
@@ -23,7 +27,7 @@ function ContactIntro() {
           </Typography>
         </Box>
         <div className={classes.marginTopSmall}>
-          <Typography variant="body1">
+          <Typography variant="body1" className={classes.contentSentence}>
```
Comment (jaasonw) [inline components/contact/ContactIntro.jsx:30]: can you add a center text alignment to this?
image

File: components/contact/ContactForm.jsx [hunk 10]
```diff
@@ -181,14 +203,15 @@ function ContactForm() {
     validateForm]);
 
   return (
-    <form id="contact-form" onSubmit={handleSubmit}>
+    <form className={classes.form} id="contact-form" onSubmit={handleSubmit}>
       <Grid container alignItems="center" justifyContent="center" direction="column">
         <Grid container alignItems="center" justifyContent="center" direction="row" spacing={2}>
           <Grid item xs={6}>
+            <InputLabel htmlFor='contact-firstname' className={classes.formLabel}>First Name*</InputLabel>
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:210]: not sure if this was a design decision i missed but i think i liked how it looked with the space next to the asterisk more

**Review by jaasonw — CHANGES_REQUESTED** [review]

File: components/contact/Contact.jsx (hunk 1 above)
Comment (bphan002) [reply components/contact/Contact.jsx]: Hi Jason,  I did this so that the sentence would not overflow on 2 lines.  I went ahead and just removed the maxWidth so that wouldn't occur.

File: components/contact/ContactForm.jsx (hunk 2 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx:18]: I went ahead and used the files from theme.

File: components/contact/ContactForm.jsx (hunk 3 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: changed

File: components/contact/ContactForm.jsx (hunk 4 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: I went ahead and set color from colors theme

File: package.json (hunk 6 above)
Comment (bphan002) [reply package.json]: removed

File: components/contact/ContactForm.jsx (hunk 7 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: I changed this to use the global theme file and set it to the size that matched the figma file

File: components/contact/ContactForm.jsx (hunk 8 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: thanks I went ahead and changed this to your suggestion

File: components/contact/ContactIntro.jsx (hunk 9 above)
Comment (bphan002) [reply components/contact/ContactIntro.jsx:33]: Done

File: components/contact/ContactForm.jsx (hunk 10 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: I believe it was a design choice.  After I checked the figma file they did not have any space next to the asterisk.

File: components/contact/ContactForm.jsx [hunk 11]
```diff
@@ -1,13 +1,39 @@
...
 import TextField from '@mui/material/TextField';
+import InputLabel from '@mui/material/InputLabel';
 import CircularProgress from '@mui/material/CircularProgress';
 import { showFeedbackSuccess, setErrorModal } from '@reducers/ui';
 import { sendGitRequest } from '@reducers/data';
 import 'react-toastify/dist/ReactToastify.css';
+import colors from '../../theme/colors';
+import fonts from '../../theme/fonts';
+import typography from '../../theme/typography';
+import borderRadius from '../../theme/borderRadius';
```
Comment (jaasonw) [inline components/contact/ContactForm.jsx:16]: Similar to line 10 in this file, prefer the import alias defined in [webpack.config.js](https://github.com/hackforla/311-data/blob/main/webpack.config.js#L22) as opposed to the relative path

ie `@theme/colors`, `@theme/fonts` etc

File: archive/aws/client/theme/colors.js [hunk 12]
```diff
@@ -13,6 +13,7 @@ export default {
   textSecondaryDark: '#A8A8A8',
   textSecondaryLight: '#ECECEC',
   textFocus: '#87C8BC',
+  formInput: '#29404F1A',
```
Comment (jaasonw) [inline archive/aws/client/theme/colors.js:16]: this is in the wrong file: `archive/aws/client/theme/colors.js`

but also @edwinjue and @ryanfchase, i was wondering why this folder exists in the first place? why not move it to a separate branch or remove it entirely? in my experience it tends to confuse the vscode autocomplete / language server

File: package-lock.json
Comment (jaasonw) [inline package-lock.json:1]: the fact that a diff still exists for package-lock.json still exists here tells me you mightve not uninstalled material-ui properly, did you use `npm uninstall` or just delete the line from package.json? either way, there should be no changes to dependencies with this pr

**Review by jaasonw — CHANGES_REQUESTED** [review]

File: components/contact/ContactForm.jsx (hunk 11 above)
Comment (bphan002) [reply components/contact/ContactForm.jsx]: Thank you so much for the detailed comments.  I've learned a lot from your pull review.

File: archive/aws/client/theme/colors.js (hunk 12 above)
Comment (bphan002) [reply archive/aws/client/theme/colors.js]: Good catch.  I went ahead and updated it.

File: package-lock.json
Comment (bphan002) [reply package-lock.json:1]: Yes, you are right with just deleting the line initially. I went ahead and uninstalled.  Thanks again!

File: archive/aws/client/theme/colors.js (hunk 12 above)
Comment (ryanfchase) [reply archive/aws/client/theme/colors.js]: @jaasonw @bphan002 just made this ticket, will this address the issue? https://github.com/hackforla/311-data/issues/1690

**Review by jaasonw — APPROVED** [review]
🚀
