### PR TITLE
Fixes: Contact form submit button does not show up when screen resolution height <= 690px

### LINKED ISSUE #1352: Contact form submit button does not show up when screen resolution height <= 690px
**Describe the bug**
Contact form `submit button` does not show up when screen resolution height <= 690px. Need to account for fixed height footer, which is blocking the submit button when there is not enough vertical real-estate to display the entire contact form

**To Reproduce**
1. Go to https://dev.311-data.org/contact
2. Zoom into the page until the submit button disappears

**Expected behavior**
Should be able to scroll down to the submit button. Presently, contact form allows one to scroll down as far as the bottom of the message box

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 105.0.5195.102 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by edwinjue**
Fixes #1352

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

File: client/components/contact/ContactForm.jsx [hunk 1]
```diff
@@ -251,6 +260,7 @@ const ContactForm = () => {
               Submit
             </Button>
           </Grid>
+          <Grid container direction="column" alignItems="center" justifyContent="center" className={classes.footer} />
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:263]: Would be great to have a comment explaining why we need to have this.

**Review by nichhk — APPROVED** [review]
Thanks Edwin! One comment. Please merge after handling it.

File: client/components/contact/ContactForm.jsx (hunk 1 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx]: updated
