### PR TITLE
1270 enable eslint on all js files (partially fixed)

### LINKED ISSUE #1270: Enable ESLint on all js files
### Overview
Many of our javascript files say `/* eslint-disable */` at the top, preventing the linter from running on them. This is a bad idea since the linter helps to identify readability issues and bugs. 

Find the full list of places where we're disabling ESLint here: https://github.com/hackforla/311-data/search?q=%22%2F*+eslint-disable+*%2F%22. **Note that we do NOT care about code in client/v1!**

After we enable ESLint on all the files, we should enable [`simple-import-sort`](https://github.com/lydell/eslint-plugin-simple-import-sort) to sort our imports.

### Action Items
- [ ] Remove `/* eslint-disable */` from all files and fix the resulting errors. We should break this up into multiple PRs--one per file, or one per directory.
- [ ] Enable `simple-import-sort` and fix resulting errors

### PR DESCRIPTION
**Pull request by edwinjue**
Partially fixes #1270

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

File: client/components/main/Desktop/TypeSelector/index.js [hunk 1]
```diff
@@ -56,65 +51,65 @@ const RequestTypeSelector = ({
...
+  };
 
-  const updateAll = (value) =>{
-      requestTypes.map(type => {
-        if(selectedTypes[type.typeId] !== value){
-          updateTypesFilter(type.typeId)
-        }
-      })
-  }
+  const updateAll = value => requestTypes.map(type => {
```
Comment (nichhk) [inline client/components/main/Desktop/TypeSelector/index.js:56]: Let's use `forEach` here since we don't need to create a new array

File: client/redux/sagas/data.js [hunk 2]
```diff
@@ -84,25 +80,25 @@ function* getFilters() {
...
-  );
-
-  return {
-    startDate,
-    endDate,
-    ncList: convertCouncilNameToID(councils),
-    requestTypes: Object.keys(requestTypes).filter(req => req !== 'All' && requestTypes[req]),
-  };
-}
+// function* getMapFilters() {
```
Comment (nichhk) [inline client/redux/sagas/data.js:83]: I'm guessing this function isn't being used? In that case, we can just delete it. Commented-out code is more confusing than useful in most cases.

**Review by nichhk — CHANGES_REQUESTED** [review]
Thanks Edwin! A couple small comments.

File: client/components/main/Desktop/TypeSelector/index.js (hunk 1 above)
Comment (edwinjue) [reply client/components/main/Desktop/TypeSelector/index.js]: sounds good, changes made

File: client/redux/sagas/data.js (hunk 2 above)
Comment (edwinjue) [reply client/redux/sagas/data.js]: agreed, commented code has been removed

File: client/components/main/Desktop/TypeSelector/index.js [hunk 3]
```diff
@@ -53,12 +53,13 @@ const RequestTypeSelector = ({
     return !isToggled;
   };
 
-  const updateAll = value => requestTypes.map(type => {
-    if (selectedTypes[type.typeId] !== value) {
-      updateTypesFilter(type.typeId);
-    }
-    return null;
-  });
+  function updateAll(value) {
```
Comment (nichhk) [inline client/components/main/Desktop/TypeSelector/index.js:56]: while you're here (I know you didn't write this): nit: value -> isSelected

**Review by nichhk — APPROVED** [review]
Thanks Edwin! One small comment. Please resolve and then feel free to merge the PR.
