### PR TITLE
remove invalid css, fix linter errors

### LINKED ISSUE #1762: Bugfix: Remove invalid CSS property in AcknowledgeModal
### Overview

We can remove an invalid CSS property in the AcknowledgeModal that is currently neither hurting nor helping the component, removing it will help clear confusion around this property

### More Info (optional)

- See @aqandrew's post in the live forever bug hunt ticket: https://github.com/hackforla/311-data/issues/1726#issuecomment-2163764526

### Action Items

- [x] Remove the invalid `fontWieght` property from the `<Typography>` component in `AcknowledgeModal.jsx`

### Resources/Instructions

Notes from the bug hunt ticket, credit @aqandrew 

> 400 is the default font weight in our typography settings. The screenshot below shows that font-weight: 400 has been set for this element already, despite the misspelled CSS property added by sx. Therefore the fontWieght entry can be safely removed from the object passed to the sx prop.

### PR DESCRIPTION
**Pull request by DrAcula27**
Fixes #1762 

### What changes did you make?
  - Removed the invalid `fontWieght` property from the `<Typography>` components in `AcknowledgeModal.jsx`
  - Fixed some linter errors caused by white-space issues

### Why did you make the changes?
  - Changes were made to clean up code and remove confusion

### Checks:
  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
- No visual changes to the modal

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

File: components/Loading/AcknowledgeModal.jsx [hunk 1]
```diff
@@ -53,10 +58,14 @@ function AcknowledgeModal({onClose}) {
   return (
     <StyledModal open={open}>
       <StyledBox>
-        <Typography variant="h6" sx={{ fontWeight: 500 }} gutterBottom>
+        <Typography variant="h6" gutterBottom>
```
Comment (ryanfchase) [inline components/Loading/AcknowledgeModal.jsx:61]: I think we're meant to keep `sx={{ fontWeight: 500 }}`, since it usefully overrides the `sx.fontWeight` property.

```suggestion
        <Typography variant="h6" sx={{ fontWeight: 500 }} gutterBottom>
```

**Review by ryanfchase — CHANGES_REQUESTED** [review]

File: components/Loading/AcknowledgeModal.jsx (hunk 1 above)
Comment (aqandrew) [reply components/Loading/AcknowledgeModal.jsx:61]: No, this change was made in the spirit of the issue 🙂

I tried it locally and it looks like the h6 default font weight is 500, so that override isn't necessary either

**Review by aqandrew — APPROVED** [review]
Approved! And good job removing the font weight override on the h6 too.

Moving forward I would recommend turning off Prettier when editing existing files, until we support Prettier project-wide.

File: components/Loading/AcknowledgeModal.jsx (hunk 1 above)
Comment (ryanfchase) [reply components/Loading/AcknowledgeModal.jsx:61]: Good catch, then we can consider this resolved!

**Review by ryanfchase — APPROVED** [review]
approved after clarification on a previous comment

**Review by Skydodle — APPROVED** [review]
Also confirmed that the fontWeight override is not needed. Looking good, thanks for cleaning up on readability @DrAcula27 !

**Comment by DrAcula27** [comment]
@ryanfchase I have Prettier set to not format on save unless I use `Ctrl + Shift + s`, so I will make sure not to enforce formatting in the future!
