### PR TITLE
Contact page fully functional. Utilizes Material UI design components and inherits styles from theme

### LINKED ISSUE #1176: Auto Create Issues of Contact Us Form Messages
### Overview
We need to automatically create issues for the project board to track inbound Contact Us form messages.

Note:
- As of Feb. 24, 2022, the v1 contact us page Send function does not work. Existing issue #1099.

### Action Items
This is a rough estimate of the work. Essentially, there are two pieces: the contact form itself, and the redux changes to execute the feedback request to our server. I think we can start by copying the old v1 contact form into v2 and resolving any build or style conflicts. Then, we can update the redux code to handle the request and response.
- [x] replace v2 contact page with [v1 contact page](https://github.com/hackforla/311-data/blob/master/client/components/contact/ContactForm.jsx)
- [x] copy API calling [code](https://github.com/hackforla/311-data/blob/master/client/redux/sagas/data.js#L210) from `master`
- [x] copy this [line](https://github.com/hackforla/311-data/blob/master/client/redux/sagas/data.js#L226) as well

### PR DESCRIPTION
**Pull request by edwinjue**
Fixes #1176 

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Contact Form (in various states):
1-Initial
2-Invalid
3-Submit
4-Confirmation

Additional toast placements:
Selection_999(2401)
Selection_999(2402)
Selection_999(2403)

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Comment by edwinjue** [comment]
in the process of writing unit tests. since this is front-end react code I am planning to use jest/react testing library instead of chai/mocha. if anybody has any experience in this area or suggestions, please feel free to chime in. would love to hear your feedback!

File: client/components/contact/ContactForm.jsx [hunk 1]
```diff
@@ -0,0 +1,270 @@
...
+    const { name, value } = event.target;
+    setFormValues(prevState => ({ ...prevState, [name]: value }));
+  }, []);
+
+  const handleSubmit = useCallback(event => {
+    event.preventDefault();
+
+    if (validateForm()) {
+      const body = [
+                `First name: ${formValues.firstName}`,
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:149]: Do we want to use the trimmed versions here?

File: client/components/contact/ContactForm.jsx [hunk 2]
```diff
@@ -0,0 +1,270 @@
...
+          missingMessage: noMessage,
+        },
+      },
+    }));
+    return false;
+  }, [formValues]);
+
+  // event handlers
+  const onInputChange = useCallback(event => {
+    event.preventDefault();
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:139]: For my understanding, can you explain what this line does?

File: client/components/contact/ContactForm.jsx [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+                onFocus={clearErrors}
+                error={formValues.errors.missingMessage}
+                helperText={formValues.errors.missingMessage ? 'Please provide a message.' : ''}
+                fullWidth
+                multiline
+              />
+            </Grid>
+          </Grid>
+          <Grid container direction="column" alignItems="center" justify="center" style={{ paddingTop: '8px' }}>
+            <CircularProgress style={{ display: formValues.loading === true ? 'block' : 'none' }} />
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:258]: can we remove `=== true`?

File: client/components/contact/ContactForm.jsx [hunk 4]
```diff
@@ -0,0 +1,270 @@
...
+    formValues.message,
+    validateForm]);
+
+  return (
+    <Container maxWidth="sm">
+      <form id="contact-form" onSubmit={handleSubmit}>
+        <Grid container alignItems="center" justify="center" direction="column" style={{ gap: '10px' }}>
+          <Grid container alignItems="center" justify="center" direction="row" spacing={2}>
+            <Grid item xs={6}>
+              <TextField
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:180]: It looks like we have multiple TextFields with some subset of the same properties. Can we make a subclass or something of that sort so that we don't need to repeat all those properties?

File: client/components/contact/ContactIntro.jsx [hunk 5]
```diff
@@ -0,0 +1,22 @@
+import React from 'react';
+import {
+  Grid,
+} from '@material-ui/core';
+
+const ContactIntro = () => (
+  <Grid container alignItems="center" justify="center" direction="column">
+    <Grid item style={{ width: '45%' }}>
+      <h1 style={{ textAlign: 'center' }}>
+        Don&apos;t See What You Need?
```
Comment (nichhk) [inline client/components/contact/ContactIntro.jsx:10]: I think the [first](https://stackoverflow.com/a/40782648) style of including a single quote is more readable

File: client/components/contact/styles/contactimage.scss [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+    position: relative;
+
+    .contact-image-overlay-text {
+    position: absolute;
+    top: 50%;
+    left: 50%;
+    transform: translate(-50%, -50%);
+    text-align: center;
+    font-size: 40px;
+    font-weight: bold;
```
Comment (nichhk) [inline client/components/contact/styles/contactimage.scss:17]: nit: indent these lines

File: client/components/contact/ContactImage.jsx [hunk 7]
```diff
@@ -0,0 +1,17 @@
+import PropTypes from 'prop-types';
+import React from 'react';
+import './styles/contactimage.scss';
+
+const ContactImage = ({ children }) => (
```
Comment (nichhk) [inline client/components/contact/ContactImage.jsx:5]: Is `children` the right name here? IIRC, `children` is being set to "Contact Us" in Contact.jsx.

File: client/components/contact/ContactForm.jsx [hunk 8]
```diff
@@ -0,0 +1,270 @@
...
+  const onInputChange = useCallback(event => {
+    event.preventDefault();
+    const { name, value } = event.target;
+    setFormValues(prevState => ({ ...prevState, [name]: value }));
+  }, []);
+
+  const handleSubmit = useCallback(event => {
+    event.preventDefault();
+
+    if (validateForm()) {
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:147]: nit: early return here would make the code a little cleaner. https://betterprogramming.pub/are-early-returns-any-good-eed4b4d03866#:~:text=Why%20Could%20You%20Consider%20Using,This%20makes%20code%20more%20readable.

File: client/components/contact/styles/contactimage.scss [hunk 9]
```diff
@@ -0,0 +1,20 @@
+
+.contact-image-cover {
```
Comment (nichhk) [inline client/components/contact/styles/contactimage.scss:2]: For now, I think it would be best to keep the codebase consistent for now and use `makeStyles` until we come to a decision about `makeStyles` vs. scss files. Wdyt?

**Review by nichhk — CHANGES_REQUESTED** [review]
Thanks Edwin, it looks great! Mostly readability comments.

Adding @jekijo as a reviewer since he has React experience as well.

Can you also put a screenshot of the form in the first comment? In general, we don't expect code reviewers to checkout a branch and bring up the frontend themselves.

File: client/components/contact/ContactForm.jsx (hunk 2 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:139]: i didn't want the default onchange event behavior to trigger. all that is required is updating the state and notice the `value` property in each TextField. the value assigned to the `value` property, which comes from the formValues state variable, gets updated whenever an onchange event happens. any time a state variable gets changed, it triggers a render() call and updates the form. disabling default onchange event behavior just prevents any potential side effects/conflicts with this process

File: client/components/contact/ContactForm.jsx [hunk 10]
```diff
@@ -0,0 +1,270 @@
...
+    invalidEmail: false,
+    missingMessage: false,
+  },
+  loading: false,
+};
+
+const ContactForm = () => {
+  // define the methods to dispatch redux actions
+  const dispatch = useDispatch();
+  const callSendGitRequest = useCallback(obj => dispatch(sendGitRequest(obj)), [dispatch]);
```
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:36]: eslint prevents lines > 100 characters so i had to be terse lol. also a bit difficult to provide anything more meaningful since payload is an generic object until it is used in a given context. i'm open to any ideas tho

File: client/components/contact/ContactForm.jsx [hunk 11]
```diff
@@ -0,0 +1,270 @@
...
+    setFormValues({
+      ...initialFormValues,
+    });
+  }
+
+  // initialize component
+  useEffect(() => {
+    // componentDidMount code goes here...
+    clearFields();
+    if (!!displayFeedbackSuccess === true) {
```
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:56]: i'm using === and !! always guarantees a truthy/falsy value (https://www.codingem.com/javascript-double-exclamation-operator/#:~:text=In%20JavaScript%2C%20the%20double%20exclamation%20operator%20converts%20an,%21%21%29%20is%20actually%20the%20not%20%28%21%29%20operator%20twice.)
in javascript true == 1, but true === 1 is not true (https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons)
using the !! prevents potential edge cases when and if displayFeedbackSuccess does not explicity return "true"

File: client/components/contact/ContactForm.jsx [hunk 12]
```diff
@@ -0,0 +1,270 @@
...
+      callShowFeedbackSuccess(false);
+      callShowErrorModal(false);
+      clearFields();
+    };
+  }, [callShowErrorModal, callShowFeedbackSuccess, displayFeedbackSuccess, openErrorModal]);
+
+  // helper methods
+  function validateEmail(emailAddress) {
+    // eslint-disable-next-line
+    if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(emailAddress)) {
```
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:91]: great idea. thanks

File: client/components/contact/ContactForm.jsx [hunk 13]
```diff
@@ -0,0 +1,270 @@
...
+      ...initialFormValues,
+    });
+  }
+
+  // initialize component
+  useEffect(() => {
+    // componentDidMount code goes here...
+    clearFields();
+    if (!!displayFeedbackSuccess === true) {
+      toast.success('We received your message. Our team will contact you at the email address provided.', {
```
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:57]: cool. creating a settings folder under contact where i will export a contactSettings object for these sort of things. we can keep a bunch of different configurations here

File: client/components/contact/ContactForm.jsx (hunk 1 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:149]: you are right. i know we're not making any system calls with the input but do you think we need to do any other sort of further input validation/sanitization? like prevent or scrub out "bad characters" like ";", "<" or "&"

File: client/components/contact/styles/contactimage.scss (hunk 9 above)
Comment (edwinjue) [reply client/components/contact/styles/contactimage.scss]: updated in the latest push

File: client/components/contact/ContactForm.jsx (hunk 3 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx]: updated in the latest version

**Comment by nichhk** [comment]
Adding @melissahermes99 in case she has any comments re: the design of the Contact page. Screenshots are in the first comment. Thanks!

File: client/components/contact/ContactForm.jsx [hunk 14]
```diff
@@ -31,13 +30,13 @@ const initialFormValues = {
 };
 
 const ContactForm = () => {
-  // define the methods to dispatch redux actions
+  // Define the methods to dispatch redux actions.
   const dispatch = useDispatch();
   const callSendGitRequest = useCallback(obj => dispatch(sendGitRequest(obj)), [dispatch]);
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:35]: I'm learning more about these hooks, and I'm wondering if it's necessary (or potentially harmful) to use `useCallback` here. It seems like `useCallback` is only useful if we're passing a function to a child component and that child component is trying to optimize render behavior in some way. Wdyt?

[redux useDispatch docs](https://react-redux.js.org/api/hooks#usedispatch)

File: client/components/contact/ContactForm.jsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (nichhk) [reply client/components/contact/ContactForm.jsx:35]: Hmm based on what I'm seeing, they are being used in specific contexts here.

line 35: obj -> gitIssueContent
line 36: o -> isSuccessful
line 37: o -> hasError

For the purpose of readability, it's better to be a little more verbose and split a line into two rather than trying to keep one line less than 100 chars. Breaking lines in js: https://stackoverflow.com/a/35167886

File: client/components/contact/ContactForm.jsx (hunk 11 above)
[the remark this answers is not in the document]
Comment (nichhk) [reply client/components/contact/ContactForm.jsx:55]: I would opt to not use type coercion here since displayFeedbackSuccess should _always_ be a bool, and if it's not, then we have a bug somewhere. It seems like converting to truthy/falsy can hide bugs in this situation, but I'm not sure about the js styles and standards here. Happy to discuss more!

File: client/components/contact/ContactForm.jsx (hunk 8 above)
Comment (nichhk) [reply client/components/contact/ContactForm.jsx:127]: Ah I didn't mean actually returning something, I just meant stopping execution early. I.e.,

```
if (!validateForm()){
    return;
}
// Do rest of the stuff in the case that form is valid...
```

Basically, in `handleSubmit`, we don't need to do anything in the case that the form is invalid, so we can make that clear by having that early return.

File: client/components/contact/ContactForm.jsx [hunk 15]
```diff
@@ -49,49 +48,31 @@ const ContactForm = () => {
...
-        pauseOnHover: true,
-        draggable: true,
-        progress: undefined,
-      });
+      toast.error('We failed to process your message. Please try again later.', contactSettings.toast.dark);
     }
 
     return () => {
-      // componentWillUnmount code goes here...
+      // ComponentWillUnmount code goes here...
```
Comment (nichhk) [inline client/components/contact/ContactForm.jsx:64]: nit: if the first word in the comment is a function, it's fine to keep it lowercase.

File: client/components/contact/ContactForm.jsx (hunk 4 above)
Comment (nichhk) [reply client/components/contact/ContactForm.jsx:160]: @jekijo or Jordan, any ideas?

File: client/components/contact/settings/index.js [hunk 16]
```diff
@@ -0,0 +1,16 @@
+// Configuration settings used by the contact page
+const contactSettings = {
```
Comment (nichhk) [inline client/components/contact/settings/index.js:2]: toastSettings ?

Also, what do you think about just having this in the ContactForm.jsx? Do you think it helps to break it out into a separate file?

**Review by nichhk — CHANGES_REQUESTED** [review]
Thanks Edwin!

File: client/components/contact/ContactForm.jsx (hunk 14 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:35]: Yes, my understanding is useCallback just caches the function so it doesn't have to be recreated at render if the dependencies in the dependencies array do not change. However, I'm getting the following eslint warnings:

```
/home/ed/311-data/client/components/contact/ContactForm.jsx
  35:9  warning  The 'callSendGitRequest' function makes the dependencies of useCallback Hook (at line 146) change on every render. Move it inside the useCallback callback. Alternatively, wrap the 'callSendGitRequest' definition into its own useCallback() Hook       react-hooks/exhaustive-deps
  36:9  warning  The 'callShowFeedbackSuccess' function makes the dependencies of useEffect Hook (at line 69) change on every render. Move it inside the useEffect callback. Alternatively, wrap the 'callShowFeedbackSuccess' definition into its own useCallback() Hook  react-hooks/exhaustive-deps
  37:9  warning  The 'callShowErrorModal' function makes the dependencies of useEffect Hook (at line 69) change on every render. Move it inside the useEffect callback. Alternatively, wrap the 'callShowErrorModal' definition into its own useCallback() Hook            react-hooks/exhaustive-deps

```
They are not technically errors so I can technically still push changes up. So, would you like me to ignore them and push up without use of useCallback(), add some eslint ignore to mute the warnings or keep as is? Thanks

File: client/components/contact/ContactForm.jsx (hunk 15 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx]: Eslint is playing games with me here. I tried a few ways to break up the lamba functions but eslint keeps recreating the one-liner and when I change the variable name, i'm exceeding 100 chars lol. Should we eslint ignore these lines?

File: client/components/contact/ContactForm.jsx (hunk 11 above)
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx]: updated in latest push

File: client/components/contact/ContactForm.jsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:35]: Eslint is playing games with me here. I tried a few ways to break up the lamba functions but eslint keeps recreating the one-liner and when I change the variable name, i'm exceeding 100 chars lol. Should we eslint ignore these lines?

File: client/components/contact/ContactForm.jsx (hunk 14 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:35]: getting rid of the lambdas and making the dispatch calls directly where needed as per discussion

Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:35]: updated in latest push

File: client/components/contact/ContactForm.jsx (hunk 15 above)
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx]: updated as discussed

File: client/components/contact/ContactForm.jsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (edwinjue) [reply client/components/contact/ContactForm.jsx:35]: updated as discussed by calling dispatch directly in respective locations instead of defining a lambda

**Review by melissahermes99 — COMMENTED** [review]
After reviewing the current Design System and the layouts we've created on Figma, this is definitely what we were hoping for! It looks great. Are we planning to go ahead with the dark mode as default for launch? And how would you feel about relocating the toast? Since we have so much happening on the top half of the screen with the photo backdrop and header, I worry the toast might get lost. However, that being said, I don't think it's the biggest issue because the form resetting also gives the notion that the form has been sent off. Other than those comments, it looks fantastic to me!

**Comment by edwinjue** [comment]
@melissahermes99 thank you so much for taking the time to review and for your feedback! 

Regarding the placement of the toast, is there a particular place you have in mind? Moving it won't be much trouble at all. We can try some other areas and I if you like, I can take some screenshots for you. Please let me know.

Also, you bring up a good point about the form resetting. I will need to run a few more tests to be sure the form is resetting only on a successful submission and not an unsuccessful one. Please also confirm this is the behavior you expect.

Thanks! Looking forward to your response

File: client/redux/reducers/metadata.js [hunk 17]
```diff
@@ -98,8 +98,9 @@ export default (state = initialState, action) => {
       };
     case types.GET_METADATA_FAILURE: {
       const {
-        response: { status },
-        message,
+        // response: { status },
```
Comment (nichhk) [inline client/redux/reducers/metadata.js:101]: nit: remove comment

File: client/redux/reducers/metadata.js [hunk 18]
```diff
@@ -98,8 +98,9 @@ export default (state = initialState, action) => {
...
+        status,
```
Comment (nichhk) [inline client/redux/reducers/metadata.js:102]: Are we extracting `status` and also assigning it to `message` here?

**Review by nichhk — APPROVED** [review]
Looks good! I'm approving it now. Please merge after addressing the small comments and Melissa's comments.

**Review by melissahermes99 — COMMENTED** [review]
@edwinjue A screenshot would be great! I've been looking at the[ Adobe suggestions ](https://spectrum.adobe.com/page/toast/)for placings toasts and I was wondering if placing it in the bottom right corner might be more effective.  My train of thought was that the user would be hitting the submit button on the lower half of the screen and their eyes would remain there for a brief second after submitting. However, because I can't fully visualize what this would look like I am unsure if that would be the right decision either. I do like the idea of including a toast if the form doesn't go through for consistency. That way the response to a successful submission also resembles an unsuccessful submission.

File: client/redux/reducers/metadata.js (hunk 18 above)
Comment (edwinjue) [reply client/redux/reducers/metadata.js:102]: [Image of console error](https://imgur.com/a/tI0bg0m)

Thanks for checking. It seems the problem is that event.response returns undefined sometimes. Therefore the status property does not exist for an undefined object. I had to update this code to the following (the one you reviewed is not ideal). The updated code will look like this:

from:
`client/redux/reducers/sagas/metadata.js`

```
  } catch (e) {
    yield put(getMetadataFailure(e));
  }

```

input variable e, the event, gets called into getMetadataFailure and the data flows into the reducer (below), where it destructures into `response` and `message` variables. in the return statement, `code` value gets set to response.status if response exists (if status is undefined, it will return undefined). if response doesn't exist, it will return response, which should be undefined. I'm sure there's a cleaner way to do this so, please let me know if you have any suggestions. But for now, I am committing these two changes in the next push.

reducer:
`client/redux/reducers/metadata.js`
```
    case types.GET_METADATA_FAILURE: {
      const {
        response,
        message
      } = action.payload;

      return {
        ...state,
        error: {
          code: !!response ? response.status : response,
          message,
          error: action.payload,
        },
      };
    }
```

**Comment by edwinjue** [comment]
@melissahermes99 I added a new section in the first comment "Additional toast placements" below the original images. Please take a look and let me know which you like best. I just found out toasts don't like being anywhere else besides around the screen border (top:left/center/right, bottom:left/center/right), so under the cover image is unfortunately out of the question.

File: client/redux/reducers/metadata.js (hunk 18 above)
Comment (nichhk) [reply client/redux/reducers/metadata.js]: Thanks for this explanation. Do you know why `event.response` is undefined sometimes? That would be something worth fixing, if possible.

It seems like this issue might be more complicated than we thought, so I prefer not to lump the fix in with this PR and open a separate issue and PR. This will make each PR easier to test and review.

Comment (edwinjue) [reply client/redux/reducers/metadata.js]: I'm not certain if it is the only time it happens but `event.response` certainly returns` undefined` when you start the client without internet connection. I did so to test whether the error toast would display correctly (which it does) but received this console error. 

Just to be clear, for now you want me to revert back all changes to the metadata.js files to the original code in the `dev` branch in my next push?

Comment (edwinjue) [reply client/redux/reducers/metadata.js]: as discussed, reverted metadata.js files back to dev branch versions in latest push

**Review by melissahermes99 — COMMENTED** [review]
The error toasts look great! Thanks for showing me all the different options, I definitely prefer the bottom right location for the toast to appear. I think everything else looks good to go!
