### PR TITLE
fixed request type strings to match database

### LINKED ISSUE #428: Update request type strings to match database
The request type strings we're displaying in the UI don't always match the `requesttype` field in the database. For example, we're using 'Dead Animal' in the UI, but the actual string in the database is 'Dead Animal Removal'.  As a result, when you search for that request type, you don't get back any data.

These are all the cases where the strings are different:

**UI string / DB string** 
Dead Animal / Dead Animal Removal
Single Streetlight / Single Streetlight Issue
Multiple Streetlight / Multiple Streetlight Issue
E-Waste / Electronic Waste
Graffiti / Graffiti Removal
Illegal Dumping / Illegal Dumping Pickup

The easy way to handle this would be just to change the strings we're displaying in the UI to match the DB strings. 

But if we want to preserve the different strings in the UI, we could modify the REQUEST_TYPES constant so that it distinguishes between the UI string and the DB string. 

```
export const REQUEST_TYPES = [
  {
     type: 'Dead Animal Removal',   // the DB string 
     display: 'Dead Animal',        // the UI string
     ...
  }
  ...
}
```

Then we could modify the components that use the request types (the RequestTypeSelector, Legend, and a bunch of the charts) to use the display string for presentation, and the type for requesting data from the backend.

P.S. the database also includes 'Report Water Waste'. Are we using that on the frontend?

### PR DESCRIPTION
**Pull request by jmensch1**
Fixes #428

The main change here is to the shape of the REQUEST_TYPES constant. As we discussed I turned it into an object, which let me remove a bunch of `.find()` statements.

```
// previously
export const REQUEST_TYPES = [
  {
    type: 'Dead Animal',
    fullType: 'Dead Animal Removal',
    abbrev: 'DAN',
    color: '#4FEFEF',
  }
...
]

// now
export const REQUEST_TYPES = {
  'Dead Animal Removal': {           // matches the database string
    displayName: 'Dead Animal',    // for UI purposes
    abbrev: 'DAN',
    color: '#4FEFEF',
  },
...
}
```
Every type has a `displayName`, so you don't have to worry about testing for a fallback. 

I also removed a couple of constants that weren't being used anywhere.

### CODE REVIEW

File: src/redux/reducers/filters.js [hunk 1]
```diff
@@ -35,39 +37,19 @@ export const updateNC = council => ({
   payload: council,
 });
 
+// set all types to either true or false
+const allRequestTypes = value => (
```
Comment (adamkendis) [inline src/redux/reducers/filters.js]: Nice, this is way better.
