### PR TITLE
Fix AcknowledgeModal to only show on initial load

### LINKED ISSUE #1707: Fix AcknowledgeModal to only show on initial load
### Overview
We need to ensure `AcknowledgeModal` is displayed only once upon the initial load of the application and does not reappear after subsequent data load or filter updates, so that users can have more smooth interaction with the map.

### More Info
We can create a flag state to track whether the modal has been shown before, initially set to `false` to always show the modal on intial load, and also condition the render to only show modal when flag is `false`. Attached the flag state's toggle to the modal's `ok` button, once user clicked the button to close the model, the flag state is set to `true` and the modal will not show again throughout the user's session.

### Action Items
- [ ] Add a new state to `MapContainer` to track if the `AcknowledgeModal` has been shown:
   - Introduce a state variable, say `acknowledgeModalShown`, to the `MapContainer` class constructor, and set it to false initially.
   - Create a method/ handler, say `onClose` to set `acknowledgeModelShown` state to true.
   - Pass the callback prop `onClose` to `AcknowledgeModal`.
- [ ] Modify the conditional rendering logic:
   - Update the ternary to render the AcknowledgeModal only if the data is done loading (isDbLoading or isMapLoading is false) and `acknowledgeModalShown` is false  (AcknowledgeModal has not shown before) . 
- [ ] Update `AcknowledgeModal` to accept a callback prop for closing:
   - `AcknowledgeModa` should accept `onClose` prop, which it calls when the modal is closed by the button handler.
 

### Resources/Instructions
- Previous issue that created the modals - #1676 
- Linked PR that closed the previous issue - #1706 

<details><summary>Demo Video of Proposed Fix</summary>
<p>

https://github.com/hackforla/311-data/assets/69279538/8566bfcf-ab1f-4d6e-a14a-f5c33f0cafbb

</p>
</details>

### PR DESCRIPTION
**Pull request by drakenguyen4000**
Fixes #1707

### What changes did you make?
- Add a new state to `MapContainer` to track if the `AcknowledgeModal` has been shown.
- Update the ternary to render the AcknowledgeModal only if the data is done loading.  
- Update `AcknowledgeModal` to accept a callback prop for closing.
 
### Why did you make the changes (we will use this info to test)?
  - To ensured that AcknowledgeModal is displayed only once upon the initial load of the application and does not reappear after subsequent data load or filter updates, so that users can have more smooth interaction with the map.
  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved
Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

File: components/Map/index.js [hunk 1]
```diff
@@ -395,13 +400,13 @@ class MapContainer extends React.Component {
           initialState={this.initialState}
         />
         <CookieNotice />
-        {(isDbLoading || isMapLoading) ? (
+        {(isDbLoading || isMapLoading) && acknowledgeModalShown === false ? (
```
Comment (Skydodle) [inline components/Map/index.js:403]: This actually disable the `LoadingModal` and `FunFactModal` after the initiial load, which is not what we want. Our goal is to disable `AcknowledgeModal` if it already has been rendered once on initial load.

We should leave line 403 as it was: 
```
{(isDbLoading || isMapLoading) ? (
```

File: components/Map/index.js [hunk 2]
```diff
@@ -395,13 +400,13 @@ class MapContainer extends React.Component {
...
           <>
             <LoadingModal />
             <FunFactCard />
           </>
         ) : (
-          <AcknowledgeModal/>
+          <AcknowledgeModal onClose={this.onClose}/>
```
Comment (Skydodle) [inline components/Map/index.js:409]: the condition `acknowledgeModalShown` should be place here at line 408 to conditionally render the `AcknowledgeModal`.

```
        ) : !acknowledgeModalShown ? (
          <AcknowledgeModal onClose={this.onClose}/>
        ) : null}
```

**Review by Skydodle — CHANGES_REQUESTED** [review]
The conditional rendering is placed at the wrong line. We DO want the `LoadingModal` & `FunFactModal` whenever the db is loading or map is loading, regardless of whether it's intial load or later during user navigation.

The goal of this issue to restrict `AcknowledgeModal` to only show up during initial load.

Please help moving the flag checking  condition to the correct line.

**Comment by drakenguyen4000** [comment]
@Skydodle Okay, I mean the changes necessary so the AcknowledgeModal only shows up the first time and not after.

**Review by sophia-bui — APPROVED** [review]
Nice work! The acknowledgement modal now displays only once on the initial load. I tested this for several random date ranges throughout the year. The loading modal and fun fact modal still appears on each search if the data/map needs to load.

**Review by Skydodle — APPROVED** [review]
Pulled down the revised PR for review. The `AcknowledgeModal` is conditionally rendered correctly in test, and code looks good. Thanks @drakenguyen4000 !
